import 'bootstrap/dist/css/bootstrap.min.css';

// import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>Hearder nextjs13</header>
        <hr />
        {children}
        <hr />
        <footer>Footer Nextjs13</footer>
      </body>
    </html>
  )
}
