
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-toastify/dist/ReactToastify.css';
import '../style/layout.scss'


import AppHeader from '@/components/app.header';
import AppFooter from '@/components/app.footer';


import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <AppHeader />
        </header>
        {children}
        <footer>
          <AppFooter />
        </footer>
        <ToastContainer
          position="top-center"
          autoClose={2000} />
      </body>
    </html>
  )
}
